In [4]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
import warnings 
warnings.filterwarnings("ignore")

In [5]:
df=pd.read_csv("movies_metadata.csv")

In [6]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [8]:
df.shape

(45466, 24)

In [10]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [12]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [13]:
df=df.drop_duplicates().reset_index(drop=True)

In [14]:
df=df[["title","tagline","overview","genres","popularity","vote_average"]]

In [15]:
df

,title,tagline,overview,genres,popularity,vote_average
0,Toy Story,NaN,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",21.946943,7.7
1,Jumanji,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",17.015539,6.9
2,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",11.7129,6.5
3,Waiting to Exhale,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",3.859495,6.1
4,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",8.387519,5.7
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",0.072051,4.0
45449,Century of Birthing,NaN,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",0.178241,9.0
45450,Betrayal,A deadly game of wits.,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",0.903007,3.8
45451,Satan Triumphant,NaN,"In a small town live two brothers, one a minis...",[],0.003503,0.0
45452,Queerama,NaN,50 years after decriminalisation of homosexual...,[],0.163015,0.0

In [16]:
df.isnull().sum()

title               6
tagline         25045
overview          954
genres              0
popularity          5
vote_average        6
dtype: int64

In [17]:
df=df.dropna(subset=["title"])

In [18]:
df.isnull().sum()

title               0
tagline         25039
overview          954
genres              0
popularity          0
vote_average        0
dtype: int64

In [19]:
df["overview"]=df["overview"].fillna("")

In [23]:
import ast
df["genres"]=df["genres"].apply(lambda x: " ".join(i['name'] for i in ast.literal_eval(x)))

In [24]:
df

,title,tagline,overview,genres,popularity,vote_average
0,Toy Story,NaN,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,21.946943,7.7
1,Jumanji,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,17.015539,6.9
2,Grumpier Old Men,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,Romance Comedy,11.7129,6.5
3,Waiting to Exhale,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,3.859495,6.1
4,Father of the Bride Part II,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,Comedy,8.387519,5.7
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman,Rising and falling between a man and woman.,Drama Family,0.072051,4.0
45449,Century of Birthing,NaN,An artist struggles to finish his work while a...,Drama,0.178241,9.0
45450,Betrayal,A deadly game of wits.,"When one of her hits goes wrong, a professiona...",Action Drama Thriller,0.903007,3.8
45451,Satan Triumphant,NaN,"In a small town live two brothers, one a minis...",,0.003503,0.0
45452,Queerama,NaN,50 years after decriminalisation of homosexual...,,0.163015,0.0

In [25]:
df["tagline"]=df["tagline"].fillna('')

In [27]:
df.isnull().sum()

title           0
tagline         0
overview        0
genres          0
popularity      0
vote_average    0
dtype: int64

In [28]:
df["tags"]=df["overview"]+" "+df["genres"]+" "+df["tagline"]

In [30]:
df["tags"][1]

"When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures. Adventure Fantasy Family Roll the dice and unleash the excitement!"

In [31]:
import nltk 
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [32]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /home/sana-
[nltk_data]     noor/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/sana-
[nltk_data]     noor/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [34]:
stop_words=set(stopwords.words("english"))
lemmatizer=WordNetLemmatizer()

In [39]:
def preprocess_text(text):
  #lowercase
  text = str(text).lower()
  #removed the punctuations
  text = re.sub(r'[^a-zA-Z\s]', '', text)

  words = text.split()
  #remove stopwords
  words = [word for word in words if word not in stop_words]

  #lemmatize
  words = [lemmatizer.lemmatize(word) for word in words]

  return " ".join(words)

In [40]:
df["tags"]=df["tags"].apply(preprocess_text)

In [42]:
df["tags"][1]

'sibling judy peter discover enchanted board game open door magical world unwittingly invite alan adult who trapped inside game year living room alans hope freedom finish game prof risky three find running giant rhinoceros evil monkey terrifying creature adventure fantasy family roll dice unleash excitement'

In [43]:
df=df.reset_index(drop=True)

In [46]:
indices=pd.Series(df.index,index=df["title"])

In [47]:
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [48]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [49]:
tfidf=TfidfVectorizer(max_features=50000,ngram_range=(1,2),stop_words='english')

In [50]:
tfidf_matrix=tfidf.fit_transform(df["tags"])

In [51]:
from sklearn.metrics.pairwise import cosine_similarity

In [52]:
def recommend(title,n=10):
    if title not in indices:
        return ["Movie not found!"]
    idx=indices[title]
    sim_score=cosine_similarity(tfidf_matrix[idx],tfidf_matrix).flatten()
    similar_idx = sim_score.argsort()[::-1][1:n+1]
    return df["title"].iloc[similar_idx]

In [54]:
recommend("Jumanji")

35576             Aschenputtel
9500                 Word Wars
21625             Table No. 21
30234          The Games Maker
37429       The Ouija Exorcism
19784    Indie Game: The Movie
15508          Le Pont du Nord
13707               Rhinoceros
8800                   Quintet
44357        Liar Game: Reborn
Name: title, dtype: object

In [55]:
import joblib
joblib.dump(tfidf,"tfidf.joblib")
joblib.dump(indices,"indices.joblib")
joblib.dump(tfidf_matrix,"tfidf_matrix.joblib")
joblib.dump(df, 'df.joblib')

['df.joblib']